const bookData = [
    {
        title: 'Zontrax',
        author_last: 'Leontine',
        author_first: 'MacScherie',
        ISBN:'292483528-3',
        library_id: 1,
    },
    {
        title: 'Flowdesk',
        author_last: 'Tracee',
        author_first: 'Lisciandri',
        ISBN:'919582683-1',
        library_id: 2,
    },
    {
        title: 'The Hobbit',
        author_last: 'Tolkien',
        author_first: 'JRR',
        ISBN:'822468845-3',
        library_id: 3,
    },
    {
        title: 'Voyatouch',
        author_last: 'Susi',
        author_first: 'Glancy',
        ISBN:'060731240-8',
        library_id: 4,
    },
    {
        title: 'Otcom',
        author_last: 'Norman', 
        author_first: 'Laverty',
        ISBN:'686382369-1',
        library_id: 5,
    },
    {
        title: 'Transcof',
        author_last: 'Felix',
        author_first: 'Sherwen',
        ISBN:'790750457-0',
        library_id: 6,
    },
    {
        title: 'Home Ing',
        author_last: 'Sherlocke',
        author_first: 'Seamon',
        ISBN:'813416748-9',
        library_id: 7,
    },
    {
        title: 'Overhold',  
        author_last: 'Anson', 
        author_first: 'Hurch',
        ISBN:'838103056-0',
        library_id: 8,
    },
    {
        title: 'Romeo and Juliette',
        author_last: 'Shakespeare',
        author_first: 'William',
        ISBN:'890882462-6',
        library_id: 9,
    },
    {
        title: 'Y-Solowarm',
        author_last: 'Ari',
        author_first: 'Kenningham',
        ISBN:'626071537-4',
        library_id: 10,
    },
    {
        title: 'Trippledex',   
        author_last: 'Merridie',
        author_first: 'Maken',
        ISBN:'691719240-6',
        library_id: 11,
    },
    {
        title: 'Transcof',
        author_last: 'Haskel',
        author_first: 'Safont',
        ISBN:'951086100-6',
        library_id: 12,
    },
    {
        title: 'Holdlamis',
        author_last: 'Isacco',
        author_first: 'Baskerfield',
        ISBN:'365499004-5',
        library_id: 13,
    },
    {
        title: 'Andalax',
        author_last: 'Bernette',
        author_first: 'Brogioni',
        ISBN: '211808717-9',
        library_id: 14,
    },
    {
        title: 'Fix San',   
        author_last: 'Ernesto',
        author_first: 'Wyeld',
        ISBN:'202810072-9',
        library_id: 15,
    },
    {
        title: 'Tres-Zap',  
        author_last: 'Maurene',
        author_first: 'Jekel',
        ISBN:'352855389-8',
        library_id: 16,
    },
    {
        title: 'Quo Lux',      
        author_last: 'Dyan',
        author_first: 'Surgison',
        ISBN:'830212365-X',
        library_id: 17,
    },
    {
        title: 'Overhold',  
        author_last: 'Rabi',
        author_first: 'Bryning',
        ISBN:'703165506-4',
        library_id: 18,
    },
    {
        title: 'Stim',   
        author_last: 'Alikee',
        author_first: 'Enders',
        ISBN:'145259906-8',
        library_id: 19,
    },
    {
        title: 'Vagram',      
        author_last: 'Fleming',
        author_first: 'Condell',
        ISBN: '414693756-6',
        library_id: 20,
    },
    {
        title: 'Flexidy',   
        author_last: 'Etienne',
        author_first: 'Cranke',
        ISBN: '816182243-3',
        library_id: 21,
    },
    {
        title: 'Overhold',      
        author_last: 'Pepe',  
        author_first: 'Freshwater',
        ISBN: '280255102-7',
        library_id: 22,
    },
    {
        title: 'Otcom',         
        author_last: 'Armstrong',
        author_first: 'Brampton',
        ISBN: '082696153-3',
        library_id: 23,
    },
    {
        title: 'Overhold',      
        author_last: 'Marcellus',
        author_first: 'Furness',
        ISBN: '503823173-X',
        library_id: 24,
    }

]

const seedBooks = () => Books.bulkcreate(bookData);

module.exports = seedBooks;