const bookData = [
    {
        title: 'Zontrax',
        author_last: 'MacScherie',
        author_first: 'Leontine',
        ISBN:'292483528-3',
        library_id: 1,
    },
    {
        title: 'Flowdesk',
        author_last: 'Lisciandri',
        author_first: 'Tracee',
        ISBN:'919582683-1',
        library_id: 2,
    },
    {
        title: 'The Hobbit',
        author_last: 'Tolkien',
        author_first: 'JRR',
        ISBN:'822468845-3',
        library_id: 3,
    },
    {
        title: 'Voyatouch',
        author_last: 'Glancy',
        author_first: 'Susi',
        ISBN:'060731240-8',
        library_id: 4,
    },
    {
        title: 'Otcom',
        author_last: 'Laverty', 
        author_first: 'Norman',
        ISBN:'686382369-1',
        library_id: 5,
    },
    {
        title: 'Transcof',
        author_last: 'Sherwen',
        author_first: 'Felix',
        ISBN:'790750457-0',
        library_id: 6,
    },
    {
        title: 'Home Ing',
        author_last: 'Seamon',
        author_first: 'Sherlocke',
        ISBN:'813416748-9',
        library_id: 7,
    },
    {
        title: 'Overhold',  
        author_last: 'Hurch', 
        author_first: 'Anson',
        ISBN:'838103056-0',
        library_id: 8,
    },
    {
        title: 'Romeo and Juliette',
        author_last: 'Shakespeare',
        author_first: 'William',
        ISBN:'890882462-6',
        library_id: 9,
    },
    {
        title: 'Y-Solowarm',
        author_last: 'Kenningham',
        author_first: 'Ari',
        ISBN:'626071537-4',
        library_id: 10,
    },
    {
        title: 'Trippledex',   
        author_last: 'Maken',
        author_first: 'Merridie',
        ISBN:'691719240-6',
        library_id: 11,
    },
    {
        title: 'Transcof',
        author_last: 'Safont',
        author_first: 'Haskel',
        ISBN:'951086100-6',
        library_id: 12,
    },
    {
        title: 'Holdlamis',
        author_last: 'Baskerfield',
        author_first: 'Isacco',
        ISBN:'365499004-5',
        library_id: 13,
    },
    {
        title: 'Andalax',
        author_last: 'Brogioni',
        author_first: 'Bernette',
        ISBN: '211808717-9',
        library_id: 14,
    },
    {
        title: 'Fix San',   
        author_last: 'Wyeld',
        author_first: 'Ernesto',
        ISBN:'202810072-9',
        library_id: 15,
    },
    {
        title: 'Tres-Zap',  
        author_last: 'Jekel',
        author_first: 'Maurene',
        ISBN:'352855389-8',
        library_id: 16,
    },
    {
        title: 'Quo Lux',      
        author_last: 'Surgison',
        author_first: 'Dyan',
        ISBN:'830212365-X',
        library_id: 17,
    },
    {
        title: 'Overhold',  
        author_last: 'Bryning',
        author_first: 'Rabi',
        ISBN:'703165506-4',
        library_id: 18,
    },
    {
        title: 'Stim',   
        author_last: 'Enders',
        author_first: 'Alikee',
        ISBN:'145259906-8',
        library_id: 19,
    },
    {
        title: 'Vagram',      
        author_last: 'Fleming',
        author_first: 'Condell',
        ISBN: '414693756-6',
        library_id: 20,
    },
    {
        title: 'Flexidy',   
        author_last: 'Cranke',
        author_first: 'Etienne',
        ISBN: '816182243-3',
        library_id: 21,
    },
    {
        title: 'Overhold',      
        author_last: 'Freshwater',  
        author_first: 'Pepe',
        ISBN: '280255102-7',
        library_id: 22,
    },
    {
        title: 'Otcom',         
        author_last: 'Armstrong',
        author_first: 'Brampton',
        ISBN: '082696153-3',
        library_id: 23,
    },
    {
        title: 'Overhold',      
        author_last: 'Furness',
        author_first: 'Marcellus',
        ISBN: '503823173-X',
        library_id: 24,
    },
    {
        title: 'Overhold',      
        author_last: 'Chritchlow',
        author_first: 'Joan',
        ISBN: '919022584-8',
        library_id: 25,
    },
    {
        title: 'Bytecard',        
        author_last: 'Robun',
        author_first: 'Constantine',
        ISBN: '437801096-8',
        library_id: 26,
    },
    {
        title: 'Flexidy',         
        author_last: 'Tosney',
        author_first: 'Latrina',
        ISBN: '452854933-6',
        library_id: 27,
    },
    {
        title: 'Temp',         
        author_last: 'Cambling',
        author_first: 'Ibbie',
        ISBN: '905164985-1',
        library_id: 28,
    },
    {
        title: 'Veribet',    
        author_last: 'Ditchburn',
        author_first: 'Dari',
        ISBN: '955429815-3',
        library_id: 29,
    },
    {
        title: 'Gembucket',         
        author_last: 'Adamsson',
        author_first: 'Derwin',
        ISBN: '525512605-5',
        library_id: 30,
    },
    {
        title: 'Andalax',         
        author_last: 'Stuckes',
        author_first: 'Melita',
        ISBN: '687156986-3',
        library_id: 31,
    },
    {
        title: 'Subin',        
        author_last: 'Gayne',
        author_first: 'Amabel',
        ISBN: '381879071-X',
        library_id: 32,
    },
    {
        title: 'Cookley',      
        author_last: 'Yokel', 
        author_first: 'Paloma',
        ISBN: '821869056-5',
        library_id: 33,
    },
    {
        title: 'Veribet',      
        author_last: 'Llorente', 
        author_first: 'Glyn',
        ISBN: '880707775-2',
        library_id: 34,
    },
    {
        title: 'Bamity',      
        author_last: 'Widdup', 
        author_first: 'Elston',
        ISBN: '828231607-5',
        library_id: 35,
    },
    {
        title: 'Daltfresh',         
        author_last: 'McColley', 
        author_first: 'Gaby',
        ISBN: '256895935-5',
        library_id: 36,
    },
    {
        title: 'Sonsing',     
        author_last: 'Pyke', 
        author_first: 'Valina',
        ISBN: '597943289-2',
        library_id: 37,
    },
    {
        title: 'Viva',      
        author_last: 'Lochrie', 
        author_first: 'Tessie',
        ISBN: '017960302-7',
        library_id: 38,
    },
    {
        title: 'Biodex',         
        author_last: 'Tomeo', 
        author_first: 'Michele',
        ISBN: '018411693-7',
        library_id: 39,
    },
    {
        title: 'Trippledex',      
        author_last: 'Borthe', 
        author_first: 'Lennie',
        ISBN: '705735996-9',
        library_id: 40,
    },
    {
        title: 'Tin',      
        author_last: 'Feldmann', 
        author_first: 'Marena',
        ISBN: '811119720-9',
        library_id: 41,
    },
    {
        title: 'Sub-Ex',     
        author_last: 'Brafferton', 
        author_first: 'Ulrikaumeko',
        ISBN: '304745449-3',
        library_id: 42,
    }

]

const seedBooks = () => Books.bulkcreate(bookData);

module.exports = seedBooks;